// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYAZvvewY2pILsHohsEv-dlrP7FOoKIP0',
    appId: '1:483214596609:web:c52fbb0d5ba562307d3e00',
    messagingSenderId: '483214596609',
    projectId: 'testpushnotification-50b4e',
    authDomain: 'testpushnotification-50b4e.firebaseapp.com',
    storageBucket: 'testpushnotification-50b4e.appspot.com',
    measurementId: 'G-J916RFE1HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgiPP6wKdIdJk0seeL20kXrnjebQnqTP0',
    appId: '1:483214596609:android:a3fc37913d5cea197d3e00',
    messagingSenderId: '483214596609',
    projectId: 'testpushnotification-50b4e',
    storageBucket: 'testpushnotification-50b4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlW9FFbEwffA0cmKBNxCK9oYU94B6Om0E',
    appId: '1:483214596609:ios:eebdf5732adcdd1a7d3e00',
    messagingSenderId: '483214596609',
    projectId: 'testpushnotification-50b4e',
    storageBucket: 'testpushnotification-50b4e.appspot.com',
    iosClientId: '483214596609-2rs991mun0vt6jf2i4oasdukm95ids9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPushNotification',
  );
}
